# render.yaml
databases:
  - name: crash-db
    databaseName: crash_game
    user: crash_user
    plan: free

services:
  - type: web
    name: crash-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/index.js
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: crash-db
          property: connectionString
      - key: BOT_TOKEN
        sync: false       # вводишь вручную в Render Dashboard
      - key: JWT_SECRET
        generateValue: true

  - type: static
    name: crash-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: crash-backend
          type: web
          property: host
